### ISSUE TITLE
My tester output

### ISSUE THREAD

**Issue by rosie-123** [cs540-testers/HW3-Tester#5]
Hi, I don't quite understand what the correct output of `n_queens_restart` should be, here below is my output
```
Tester V1.0
Elapsed time was: 0.46607s
Reference runtime is ~0.75s
See diff below. If you see nothing but the end message, you're good.
***
---
***************
*** 80,83 ****
[0, 6, 3, 7, 2, 4, 5, 1] - f=2
[0, 6, 4, 2, 7, 5, 3, 1] - f=2
n_queens_restart tests complete
-
--- 80,82 ----
This is the end of the tester.
```
Anyone can share some thoughts? Thank you!

**Comment by alexmoon01** [comment]
You can see the correct output [here](https://github.com/cs540-testers/HW3-Tester/blob/master/ref.txt). This may have been updated since you opened the issue, so make sure to pull from master one more time and run again to see if anything changed. It looks to me like you're very close, with only one discrepancy on [line 81](https://github.com/cs540-testers/HW3-Tester/blob/1c40608789099cb97fc6bd70ae278d456a01d61b/ref.txt#L81). If your output matches our ref.txt exactly, then you will not see any [a, b, ...] f=k output from the test.

**Comment by rosie-123** [comment]
> You can see the correct output [here](https://github.com/cs540-testers/HW3-Tester/blob/master/ref.txt). This may have been updated since you opened the issue, so make sure to pull from master one more time and run again to see if anything changed. It looks to me like you're very close, with only one discrepancy on [line 81](https://github.com/cs540-testers/HW3-Tester/blob/1c40608789099cb97fc6bd70ae278d456a01d61b/ref.txt#L81). If your output matches our ref.txt exactly, then you will not see any [a, b, ...] f=k output from the test.

Thank you! I pulled the newest test file, and got the result as below
```
Tester V1.1
Elapsed time was: 0.48327s
Reference runtime is ~0.291s
See diff below. If you see nothing but the end message, you're good.
This is the end of the tester.
```
I think my code is fine now except being a little slow, thank you!
